services:
  - type: web
    name: script-ai-api
    env: python
    plan: free
    region: oregon
    buildCommand: |
      pip install --no-cache-dir -r requirements.txt
    startCommand: bash start.sh
    
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: TRANSFORMERS_CACHE
        value: "/tmp/transformers_cache"
      - key: HF_HOME
        value: "/tmp/huggingface"
    
    healthCheckPath: /health
